import JSZip from "jszip";
import { FragmentFiles } from "@/schemas/fragment-files";

/**
 * Generate a README.md file for the exported project
 */
export function generateReadme(projectName: string, files: FragmentFiles): string {
    const fileList = Object.keys(files)
        .map(path => `- ${path}`)
        .join("\n");

    return `# ${projectName}

This project was generated by DevFlow - an AI-powered coding environment.

## 📁 Project Structure

${fileList}

## 🚀 Getting Started

### Prerequisites
- Node.js 18+ installed
- npm or yarn package manager

### Installation

1. Extract this ZIP file to your desired location
2. Open terminal in the project directory
3. Install dependencies:

\`\`\`bash
npm install
\`\`\`

### Development

Run the development server:

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

### Build for Production

\`\`\`bash
npm run build
npm start
\`\`\`

## 📝 Notes

- This is a Next.js 16 application (App Router, Turbopack)
- Uses Tailwind CSS for styling
- Generated on ${new Date().toLocaleDateString()}

## 🔗 Resources

- [Next.js Documentation](https://nextjs.org/docs)
- [DevFlow](https://devflow.app)

---

Generated with ❤️ by DevFlow
`;
}

/**
 * Extract dependencies from package.json files
 */
export function extractDependencies(files: FragmentFiles): Record<string, string> {
    const packageJsonPath = Object.keys(files).find(
        path => path.endsWith("package.json")
    );

    if (packageJsonPath) {
        try {
            const content = JSON.parse(files[packageJsonPath]);
            return content.dependencies || {};
        } catch (error) {
            console.error("Failed to parse package.json:", error);
        }
    }

    // Default Next.js 16 dependencies
    return {
        "next": "^16.1.4",
        "react": "^19.2.3",
        "react-dom": "^19.2.3",
    };
}

/**
 * Generate a package.json file for the exported project
 */
export function generatePackageJson(
    projectName: string,
    files: FragmentFiles
): string {
    const dependencies = extractDependencies(files);

    const packageJson = {
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        version: "0.1.0",
        private: true,
        scripts: {
            dev: "next dev --turbopack",
            build: "next build",
            start: "next start",
            lint: "next lint",
        },
        dependencies: {
            ...dependencies,
            // Ensure Tailwind is included
            "tailwindcss": "^3.4.1",
            "postcss": "^8.4.35",
            "autoprefixer": "^10.4.17",
        },
        devDependencies: {
            "@types/node": "^20",
            "@types/react": "^19",
            "@types/react-dom": "^19",
            "typescript": "^5",
        },
    };

    return JSON.stringify(packageJson, null, 2);
}

/**
 * Generate Tailwind configuration file
 */
export function generateTailwindConfig(): string {
    return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
}

/**
 * Generate PostCSS configuration file
 */
export function generatePostCSSConfig(): string {
    return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}

/**
 * Generate Next.js configuration file
 */
export function generateNextConfig(): string {
    return `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
`;
}

/**
 * Export project as ZIP file
 */
export async function exportProjectAsZip(
    projectName: string,
    files: FragmentFiles
): Promise<void> {
    const zip = new JSZip();

    // Add all project files
    Object.entries(files).forEach(([filepath, content]) => {
        zip.file(filepath, content);
    });

    // Add README.md
    const readme = generateReadme(projectName, files);
    zip.file("README.md", readme);

    // Add/Update package.json
    const packageJson = generatePackageJson(projectName, files);
    zip.file("package.json", packageJson);

    // Add configuration files
    zip.file("tailwind.config.js", generateTailwindConfig());
    zip.file("postcss.config.js", generatePostCSSConfig());
    zip.file("next.config.js", generateNextConfig());

    // Generate ZIP blob
    const blob = await zip.generateAsync({ type: "blob" });

    // Trigger download
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${projectName.replace(/\s+/g, "-")}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
